export const cst = {
    FACTION_BROBNAR: {name:"Brobnar",url:"../assets/imgs/logo_brobnar.png"},
    FACTION_LOGOS: {name:"Logos",url:"../assets/imgs/logo_logos.png"},
    FACTION_SANCTUM: {name:"Sanctum",url:"../assets/imgs/logo_sanctum.png"},
    FACTION_UNTAMED: {name:"Untamed",url:"../assets/imgs/logo_untamed.png"},
    FACTION_SHADOW: {name:"Shadows",url:"../assets/imgs/logo_shadow.png"},
    FACTION_MARS: {name:"Mars",url:"../assets/imgs/logo_mars.png"},
    FACTION_DIS: {name:"Dis",url:"../assets/imgs/logo_dis.png"},
    WIN_PICTO: "../assets/imgs/key_win.png",
    DRAW_PICTO: "../assets/imgs/key_draw.png",
    GAME_WIN: "Win",
    GAME_LOOSE: "Lose",
    GAME_DRAW: "Draw",
    TBL_PLAYER: "player",
    TBL_DECK: "deck",
    TBL_MATCH: "match",
    TBL_STATS: "stats",
    TBL_SUGGESTIONS: "suggestions",
    CHAIN: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
}
